var y=Object.defineProperty;var L=(t,e,s)=>e in t?y(t,e,{enumerable:!0,configurable:!0,writable:!0,value:s}):t[e]=s;var n=(t,e,s)=>L(t,typeof e!="symbol"?e+"":e,s);import{a as I,i as l,S as b}from"./assets/vendor-Dp7Ig4E2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))u(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const m of a.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&u(m)}).observe(document,{childList:!0,subtree:!0});function s(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function u(r){if(r.ep)return;r.ep=!0;const a=s(r);fetch(r.href,a)}})();class w{constructor(e){n(this,"BASE_URL","https://pixabay.com/api/");n(this,"currentPage",1);n(this,"resultsPerPage",15);n(this,"totalPages",0);n(this,"query","");this.apiKey=e}async getImageList(){const e={params:{key:this.apiKey,q:this.query,image_type:"photo",orientation:"horizontal",safesearch:"true",page:this.currentPage,per_page:this.resultsPerPage}};try{const s=await I.get(this.BASE_URL,e);return this.totalPages=Math.ceil(s.data.totalHits/15),s.data.hits}catch{throw new Error("something went wrong")}}}function f(t){return t.length<=0?(l.error({message:"Sorry, there are no images matching your search query. Please try again!",progressBar:!1,transitionIn:"fadeIn",position:"topRight"}),"no images found"):t.map(s=>`<li class="gallery-item">
            <a class="gallery-link" href="${s.largeImageURL}">
              <img src="${s.webformatURL}" alt="${s.tags}" width="360" height="200">
            </a>
            <ul class="gallery-item-desc">
              <li class="gallery-item-desc-item"><span class="gallery-item-desc-cap">Likes</span><span>${s.likes}</span></li>
              <li class="gallery-item-desc-item"><span class="gallery-item-desc-cap">Views</span><span>${s.views}</span></li>
              <li class="gallery-item-desc-item"><span class="gallery-item-desc-cap">Comments</span><span>${s.comments}</span></li>
              <li class="gallery-item-desc-item"><span class="gallery-item-desc-cap">Downloads</span><span>${s.downloads}</span></li>
            </ul>
          </li>`).join("")}function p(t,e){e.insertAdjacentHTML("beforeend",t)}const d=document.querySelector(".gallery-list"),P=document.querySelector(".search-form-input"),q=document.querySelector(".search-form"),c=document.querySelector(".loader"),g=document.querySelector(".load-more-button"),S="44799740-e5447d6b9b58b3b9f4f848c49",i=new w(S),h=new b(".gallery-list a",{captionDelay:250,captionsData:"alt"});async function v(t){if(t.preventDefault(),d.innerHTML="",i.currentPage=1,i.query=P.value,o(g,!1),E(i.query))try{o(c,!0);const e=await i.getImageList();if(o(c,!1),e.length>0){const s=f(e);p(s,d),h.refresh(),i.totalPages>1&&o(g,!0)}else l.info({message:"No images found",progressBar:!1,transitionIn:"fadeIn",position:"topRight"})}catch(e){o(c,!1),l.error({message:`Error occurred while searching for images: ${e.message}`,progressBar:!1,transitionIn:"fadeIn",position:"topRight"})}else l.error({message:"Search attribute is not valid",progressBar:!1,transitionIn:"fadeIn",position:"topRight"})}async function B(t){t.preventDefault(),i.currentPage+=1,o(c,!0),o(g,!1);try{const e=await i.getImageList();o(c,!1);const s=f(e);p(s,d),h.refresh();const u=document.querySelector(".gallery-item");window.scrollBy({top:u.getBoundingClientRect().height*2,behavior:"smooth"}),i.totalPages===i.currentPage?(o(g,!1),l.info({message:"We're sorry, but you've reached the end of search results.",progressBar:!1,transitionIn:"fadeIn",position:"topRight"})):o(g,!0)}catch(e){o(c,!1),l.error({message:`Error occurred while loading more images: ${e.message}`,progressBar:!1,transitionIn:"fadeIn",position:"topRight"})}}function E(t){return t.trim()!==""}function o(t,e=!1){t?e?t.classList.remove("hidden"):t.classList.add("hidden"):console.error("Element not found:",t)}q.addEventListener("submit",v);g.addEventListener("click",B);
//# sourceMappingURL=index.js.map
