var y=Object.defineProperty;var I=(t,e,s)=>e in t?y(t,e,{enumerable:!0,configurable:!0,writable:!0,value:s}):t[e]=s;var l=(t,e,s)=>I(t,typeof e!="symbol"?e+"":e,s);import{a as L,i as n,S as P}from"./assets/vendor-Dp7Ig4E2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))u(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const m of a.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&u(m)}).observe(document,{childList:!0,subtree:!0});function s(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function u(r){if(r.ep)return;r.ep=!0;const a=s(r);fetch(r.href,a)}})();class b{constructor(e){l(this,"BASE_URL","https://pixabay.com/api/");l(this,"currentPage",1);l(this,"resultsPerPage",15);l(this,"totalPages",0);l(this,"query","");this.apiKey=e}async getImageList(){const e={params:{key:this.apiKey,q:this.query,image_type:"photo",orientation:"horizontal",safesearch:"true",page:this.currentPage,per_page:this.resultsPerPage}};try{const s=await L.get(this.BASE_URL,e);return this.totalPages=Math.ceil(s.data.totalHits/15),s.data.hits}catch{throw new Error("something went wrong")}}}function d(t){return t.length<=0?(n.error({message:"Sorry, there are no images matching your search query. Please try again!",progressBar:!1,transitionIn:"fadeIn",position:"topRight"}),"no images found"):t.map(s=>`<li class="gallery-item">
            <a class="gallery-link" href="${s.largeImageURL}">
              <img src="${s.webformatURL}" alt="${s.tags}" width="360" height="200">
            </a>
            <ul class="gallery-item-desc">
              <li class="gallery-item-desc-item"><span class="gallery-item-desc-cap">Likes</span><span>${s.likes}</span></li>
              <li class="gallery-item-desc-item"><span class="gallery-item-desc-cap">Views</span><span>${s.views}</span></li>
              <li class="gallery-item-desc-item"><span class="gallery-item-desc-cap">Comments</span><span>${s.comments}</span></li>
              <li class="gallery-item-desc-item"><span class="gallery-item-desc-cap">Downloads</span><span>${s.downloads}</span></li>
            </ul>
          </li>`).join("")}function p(t,e){e.insertAdjacentHTML("beforeend",t)}const f=document.querySelector(".gallery-list"),w=document.querySelector(".search-form-input"),q=document.querySelector(".search-form"),c=document.querySelector(".loader"),g=document.querySelector(".load-more-button"),S="44799740-e5447d6b9b58b3b9f4f848c49",o=new b(S),h=new P(".gallery-list a",{captionDelay:250,captionsData:"alt"});async function v(t){if(t.preventDefault(),f.innerHTML="",o.currentPage=1,o.query=w.value,i(g,!1),R(o.query)){i(c,!0);try{const e=await o.getImageList();if(i(c,!1),e.length>0){const s=d(e);p(s,f),h.refresh(),o.totalPages>1&&i(g,!0)}else n.info({message:"No images found",progressBar:!1,transitionIn:"fadeIn",position:"topRight"})}catch(e){i(c,!1),n.error({message:"An error occurred while fetching images. Please try again later.",progressBar:!1,transitionIn:"fadeIn",position:"topRight"}),console.error("Error fetching images:",e)}}else n.error({message:"Search attribute is not valid",progressBar:!1,transitionIn:"fadeIn",position:"topRight"})}async function B(t){t.preventDefault(),o.currentPage+=1,i(c,!0),i(g,!1);try{const e=await o.getImageList();if(i(c,!1),e.length>0){const s=d(e);p(s,f),h.refresh();const u=document.querySelector(".gallery-item");u&&window.scrollBy({top:u.getBoundingClientRect().height*2,behavior:"smooth"}),o.totalPages===o.currentPage?(i(g,!1),n.info({message:"We're sorry, but you've reached the end of search results.",progressBar:!1,transitionIn:"fadeIn",position:"topRight"})):i(g,!0)}else n.info({message:"No more images found",progressBar:!1,transitionIn:"fadeIn",position:"topRight"})}catch(e){i(c,!1),n.error({message:"An error occurred while loading more images. Please try again later.",progressBar:!1,transitionIn:"fadeIn",position:"topRight"}),console.error("Error loading more images:",e)}}function R(t){return t.trim()!==""}function i(t,e=!1){e?t.classList.remove("hidden"):t.classList.add("hidden")}q.addEventListener("submit",v);g.addEventListener("click",B);
//# sourceMappingURL=index.js.map
